---
- name: apt install ansible stuff and git
  apt: name=ansible update_cache=yes state=latest
  apt: name=git update_cache=yes state=latest
- name: Clone a public repository into ansible.
  git:
    repo: http://'{{gituser}}':'{{gitpass}}'@github.com/computer1up/ansible
    version: master
    dest: /home/gr06admin/ansible
    #accept_hostkey: yes
    #key_file: /home/gr06admin/.ssh/id_rsa
  become_user: gr06admin
#th2g47j4lelobpfvtw5rnqokwgw4jqgaprpi73txfqamrt4a4d6q
#https://qnh-vsts-kg-edu.visualstudio.com/QNH-TP-Group06-EDU/_git/QNH-TP-Group06-EDU
