---
- name: Deploy ansible and playbook
  sudo: yes
  - name: apt install ansible stuff and git
    apt: name=ansible update_cache=yes state=latest
    apt: name=git update_cache=yes state=latest
  - name: Clone a public repository into ansible.
    git:
      repo: git@github.com:computer1up/ansible.git
      version: master
      dest: /home/gr06admin/ansible
      accept_hostkey: yes
      key_file: /home/gr06admin/.ssh/id_rsa
    become_user: gr06admin
