---
- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: zuyrg00006
    allocation_method: Static
    name: NW-PUB-ANS002
  register: output_ip_address
- name: Dump public IP for VM which will be created
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."
- name: add host to memory
  add_host:
    name: "{{output_ip_address.state.ip_address}}"
    groups: ans
- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: zuyrg00006
    name: NW-VNIC-006
    virtual_network: NW-VNET-001
    subnet: Front-end
    security_group: NW-NSG-002
    ip_configurations:
      - name: ansconf
        public_ip_address_name: NW-PUB-ANS002
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: zuyrg00006
    name: NW-ANS-002
    vm_size: Standard_B1s
    admin_username: gr06admin
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/gr06admin/.ssh/authorized_keys
        key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCwW2vYA4yTvtZmCPYQNEbOD53ayTXJn6Jb3+Lm7psxhovXdo2ydLQHOfsILlHcO7dSofc/nytXzZR25q/P1tIoV58M11oR46PbdbNSoeRtAoiXI7YvQKtCbJRXgABkWzgGTdpE8BDE2ssG/NoCJHLK8iY+cCWGpDnDUVad4GvyDw== remydoon@rd-MacBook-Pro.local
    network_interfaces: NW-VNIC-006
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: '18.04-LTS'
      version: latest
- name: Deploy ansible and playbook
  hosts: ans
  sudo: yes
  tasks:
    - name: apt install ansible stuff and git
      apt: name=ansible update_cache=yes state=latest
      apt: name=git update_cache=yes state=latest
    - name: Clone a public repository into ansible.
      git:
        repo: git@github.com:computer1up/ansible.git
        version: master
        dest: /home/gr06admin/ansible
        accept_hostkey: yes
        key_file: /home/gr06admin/.ssh/id_rsa
      become_user: gr06admin
