---
- name: Main playbook
  hosts: localhost
  connection: local
  roles:
    - role: vnet
    - role: nsg001
    - role: nsg002
    - role: pubip
    - role: storageaccount
    - role: subnet-ba
    - role: subnet-fr
    - role: http003
    - role: http004
    - role: addc-server
    - role: sql
- name: ADDC Install
  hosts: addc
  roles:
    - role: addc-software
- name: IIS Install
  hosts: webservers
  roles:
    - roles: addc-join
    - roles: iis
