---
- name: Main playbook
  hosts: localhost
  connection: local
  roles:
    - role: vnet
    - role: nsg001
    - role: nsg002
    - role: pubip
    - role: storageaccount
    - role: subnet-ba
    - role: subnet-fr
    - role: lb
    - role: http003
    - role: http004
#    - role: ansible-server
    - role: addc-server
    - role: sql
- name: ansible Install
  hosts: ans
  sudo: yes
  roles:
    - role: ansible-software
- name: ADDC Install
  hosts: addc
  include_vars:
    file: vars/secret.yaml
  ansible_user: gr06admin
  ansible_password: "{{ adminpass }}"
  ansible_connection: winrm
  ansible_winrm_transport: basic
  roles:
    - role: addc-software
- name: IIS Install
  include_vars:
    file: vars/secret.yaml
  ansible_user: gr06admin
  ansible_password: "{{ adminpass }}"
  ansible_connection: winrm
  ansible_winrm_transport: basic
  hosts: webservers
  roles:
    - role: addc-join
    - role: iis
