---
- name: install iis-server
  include_vars:
    file: vars/secret.yaml
  ansible_user: gr06admin
  ansible_password: "{{ adminpass }}"
  ansible_connection: winrm
  ansible_winrm_transport: basic
  win_feature:
    name: Web-Server
    include_sub_features: True
    state: present
  register: win_feature_installed
  win_reboot:
    when: win_feature_installed.reboot_required
