- name: Remove Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Remove VM
      azure_rm_virtualmachine:
        resource_group: zuyrg00006
        name: rdtestvm01
        state: absent
    - name: Remove virtual network inteface card
      azure_rm_networkinterface:
        resource_group: zuyrg00006
        name: rdtestnic01
        state: absent
    - name: Remove subnet
      azure_rm_subnet:
        resource_group: zuyrg00006
        virtual_network_name: rdtestvnet01
        name: rdtestsubnet01
        state: absent
    - name: Remove virtual network
      azure_rm_virtualnetwork:
        resource_group: zuyrg00006
        name: rdtestvnet01
        state: absent
    - name: Remove public IP address
      azure_rm_publicipaddress:
        resource_group: zuyrg00006
        name: rdtetpubip01
        state: absent
    - name: Remove Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: zuyrg00006
        name: rdtestsecgr01
        state: absent
    - name: Remove storage account
      azure_rm_storageaccount:
        resource_group: zuyrg00006
        name: rdteststorage01
        state: absent