---
- name: include vars
  include_vars:
    file: vars/secret.yaml
- name: Install AD Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result
- name: Create new forest
  win_domain:
    dns_domain_name: newways02.com
    safe_mode_password: "{{adminpass}}"
  register: result
- name: Reboot after creation
  win_reboot:
    msg: "Server config in progress; rebooting..."
  when: result.reboot_required
- name: Ensure user bob is present with address information
  win_domain_user:
    name: remy
    firstname: Remy
    surname: Doon
    password: SomePass123
    state: present
    groups:
      - Domain Admins
